#!/usr/bin/env bash
# Run Nginx as Nginx
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chmod 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
chmod 000 /etc/nginx/nginx.conf
